# All Lights Software Switch
  - platform: template
    switches:
      bathroom_automation:
        value_template: "{{ is_state('automation.turn_off_bathroom_light_2_minutes', 'on') }}"
        turn_on:
          - service: automation.turn_on
            entity_id: automation.turn_off_bathroom_light_2_minutes
        turn_off:
          - service: automation.turn_off
            entity_id: automation.turn_off_bathroom_light_2_minutes
