# Bathroom Sensor Automations
- alias: Turn on bathroom light morning
  trigger:
    platform: state
    entity_id: sensor.bathroom_motion_sensor
    to: 'on'
  condition:
  - below: '10'
    condition: numeric_state
    entity_id: sensor.bathroom_light_level
  - condition: state
    entity_id: light.bathroom
    state: 'off'
  - condition: time
    after: '07:00:00'
    before: '08:59:00'
  action:
    service: homeassistant.turn_on
    entity_id: light.bathroom
    data_template:
      brightness: 130
      color_temp: 318
      transition: 5

- alias: Turn on bathroom light day
  trigger:
    platform: state
    entity_id: sensor.bathroom_motion_sensor
    to: 'on'
  condition:
  - below: '30'
    condition: numeric_state
    entity_id: sensor.bathroom_light_level
  - condition: state
    entity_id: light.bathroom
    state: 'off'
  - condition: time
    after: '09:00:00'
    before: '23:29:00'
  action:
    service: homeassistant.turn_on
    entity_id: light.bathroom
    data_template:
      brightness: 254
      color_temp: 318
      transition: 5

- alias: Turn on bathroom light night
  trigger:
    platform: state
    entity_id: sensor.bathroom_motion_sensor
    to: 'on'
  condition:
  - below: '5'
    condition: numeric_state
    entity_id: sensor.bathroom_light_level
  - condition: state
    entity_id: light.bathroom
    state: 'off'
  - condition: time
    after: '23:30:00'
    before: '06:59:00'
  action:
    service: homeassistant.turn_on
    entity_id: light.bathroom
    data_template:
      brightness: 15
      color_temp: 318
      transition: 30

- alias: Turn off bathroom light 5 minutes
  trigger:
    platform: state
    entity_id: sensor.bathroom_motion_sensor
    to: 'off'
    for:
      minutes: 5
  action:
    service: homeassistant.turn_off
    entity_id: light.bathroom
    data_template:
      transition: 30

# Hall Sensor Automations
- alias: Turn on hall lights morning
  trigger:
    platform: state
    entity_id: sensor.hall_motion_sensor
    to: 'on'
  condition:
  - below: '10'
    condition: numeric_state
    entity_id: sensor.hall_light_level
  - condition: state
    entity_id: light.hallway_spot_1
    state: 'off'
  - condition: state
    entity_id: light.hallway_spot_2
    state: 'off'
  - condition: time
    after: '07:00:00'
    before: '09:59:00'
  action:
    service: homeassistant.turn_on
    entity_id: light.hallway_spot_1, light.hallway_spot_2
    data_template:
      brightness: 130
      color_temp: 318
      transition: 5

- alias: Turn on hall lights day
  trigger:
    platform: state
    entity_id: sensor.hall_motion_sensor
    to: 'on'
  condition:
  - below: '20'
    condition: numeric_state
    entity_id: sensor.hall_light_level
  - condition: state
    entity_id: light.hallway_spot_1
    state: 'off'
  - condition: state
    entity_id: light.hallway_spot_2
    state: 'off'    
  - condition: time
    after: '09:00:00'
    before: '23:29:00'
  action:
    service: homeassistant.turn_on
    entity_id: light.hallway_spot_1, light.hallway_spot_2
    data_template:
      brightness: 254
      color_temp: 318
      transition: 5

- alias: Turn on hall lights night
  trigger:
    platform: state
    entity_id: sensor.hall_motion_sensor
    to: 'on'
  condition:
  - below: '5'
    condition: numeric_state
    entity_id: sensor.hall_light_level
  - condition: state
    entity_id: light.hallway_spot_1
    state: 'off'
  - condition: state
    entity_id: light.hallway_spot_2
    state: 'off'
  - condition: time
    after: '23:30:00'
    before: '06:59:00'
  action:
    service: homeassistant.turn_on
    entity_id: light.hallway_spot_1, light.hallway_spot_2
    data_template:
      brightness: 10
      rgb_color: [255, 0, 0]
      transition: 5

- alias: Turn off hall lights 2 minutes
  trigger:
    platform: state
    entity_id: sensor.hall_motion_sensor
    to: 'off'
    for:
      minutes: 2
  action:
    service: homeassistant.turn_off
    entity_id: light.hall_spotlights
    data_template:
      transition: 30

#Landing Sensor Automations
- alias: Turn on landing lights morning
  trigger:
    platform: state
    entity_id: sensor.landing_motion_sensor
    to: 'on'
  condition:
  - below: '10'
    condition: numeric_state
    entity_id: sensor.landing_light_level
  - condition: state
    entity_id: light.landing_spot
    state: 'off'
  - condition: time
    after: '07:00:00'
    before: '09:59:00'
  action:
    service: homeassistant.turn_on
    entity_id: light.landing_spot
    data_template:
      brightness: 130
      color_temp: 318
      transition: 5

- alias: Turn on landing lights day
  trigger:
    platform: state
    entity_id: sensor.landing_motion_sensor
    to: 'on'
  condition:
  - below: '20'
    condition: numeric_state
    entity_id: sensor.landing_light_level
  - condition: state
    entity_id: light.landing_spot
    state: 'off'
  - condition: time
    after: '09:00:00'
    before: '23:29:00'
  action:
    service: homeassistant.turn_on
    entity_id: light.landing_spot
    data_template:
      brightness: 254
      color_temp: 318
      transition: 5

- alias: Turn on landing lights night
  trigger:
    platform: state
    entity_id: sensor.landing_motion_sensor
    to: 'on'
  condition:
  - below: '5'
    condition: numeric_state
    entity_id: sensor.landing_light_level
  - condition: state
    entity_id: light.landing_spot
    state: 'off'
  - condition: time
    after: '23:30:00'
    before: '06:59:00'
  action:
    service: homeassistant.turn_on
    entity_id: light.landing_spot
    data_template:
      brightness: 10
      rgb_color: [255, 0, 0]
      transition: 5

- alias: Turn off landing lights 2 minutes
  trigger:
    platform: state
    entity_id: sensor.landing_motion_sensor
    to: 'off'
    for:
      minutes: 2
  action:
    service: homeassistant.turn_off
    entity_id: light.landing_spot
    data_template:
      transition: 30

- alias: Long Press OFF Bedroom Remote
  trigger:
    platform: state
    entity_id: sensor.bedroom_switch
    to: '4_hold'
  action:
    service: homeassistant.turn_off
    entity_id: switch.downstairs_lights




- alias: Abi Is Home
  trigger:
    platform: state
    entity_id: sensor.abi_connected_ap
    from: Offline
    to: 'LIVING_ROOM_WIFI'
  action:
    service: tts.google_say
    entity_id: media_player.living_room_home
    data:
      message: 'Welcome Home.'


- alias: Heating on notification
  trigger:
    platform: state
    entity_id: sensor.living_room_thermostat_hvac_state
    to: heating
  action:
    service: hangouts.send_message
    data_template:
      target: 
      - id: !secret notifier_noodlemctwoodle
      message: 
        - text: "The heating is on"
      
- alias: Abi is home notification
  trigger:
    platform: state
    entity_id: device_tracker.google_pixel_abi
    to: home
  action:
    service: hangouts.send_message
    data_template:
      target: 
      - id: !secret notifier_noodlemctwoodle
      message: 
        - text: "Abi is home"

    
      

#- alias: Toby Is Home
#  trigger:
#    platform: numeric_state
#    entity_id: sensor.toby_presence
#    above: '10'
#  condition:
#  - below: '50'
#    condition: numeric_state
#    entity_id: sensor.abi_presence
#  - below: '50'
#    condition: numeric_state
#    entity_id: sensor.toby_presence
#  action:
#    service: homeassistant.turn_on
#    entity_id: light.hallway_spot_1, light.hallway_spot_2
#    data_template:
#      brightness: 254
#      color_temp: 318

