- alias: Plex Webhook
  trigger:
  - platform: webhook
    webhook_id: plex-shield
  condition: []
  action:
    service: homeassistant.turn_on
    entity_id: light.living_room_lamp
    data_template:
      brightness: 40
      color_temp: 318
      transition: 30
