# Philips Hue Motion Sensor - RestAPI (Custom-Component)
## https://github.com/robmarkcole/Hue-sensors-HASS ##

- platform: hue
  ip_address: !secret hue_bridge_ip
  token: !secret hue_bridge_password

- platform: template
  sensors:
# Bathroom Sensor  
    bathroom_temperature:
      friendly_name: 'Bathroom temperature'
      value_template: '{{states.sensor.bathroom_motion_sensor.attributes.temperature}}'
      unit_of_measurement: °C
    bathroom_light_level:
      friendly_name: 'Bathroom light level'
      value_template: '{{states.sensor.bathroom_motion_sensor.attributes.lx}}'
      unit_of_measurement: lux
    bathroom_battery_level:
      friendly_name: 'Bathroom battery level'
      value_template: '{{states.sensor.bathroom_motion_sensor.attributes.battery}}'
      unit_of_measurement: '%'   
# Landing Sensor
    landing_temperature:
      friendly_name: 'Landing temperature'
      value_template: '{{states.sensor.landing_motion_sensor.attributes.temperature}}'
      unit_of_measurement: °C
    landing_light_level:
      friendly_name: 'Landing light level'
      value_template: '{{states.sensor.landing_motion_sensor.attributes.lx}}'
      unit_of_measurement: lux
    landing_battery_level:
      friendly_name: 'Landing battery level'
      value_template: '{{states.sensor.landing_motion_sensor.attributes.battery}}'
      unit_of_measurement: '%' 
# Kitchen Hue Remote
    kitchen_switch_battery_level:
      friendly_name: 'Kitchen Remote Battery'
      value_template: '{{states.sensor.kitchen_switch.attributes.battery}}'
      unit_of_measurement: '%'
    kitchen_remote:
      friendly_name: Hue Kitchen Remote
      value_template: '{% if is_state("sensor.kitchen_switch", "1_click_up") %} 
          Quick Click 1
        {% elif is_state("sensor.kitchen_switch", "1_hold") %}
          Hold Click 1
        {% elif is_state("sensor.kitchen_switch", "2_click_up") %}
          Quick Click 2
        {% elif is_state("sensor.kitchen_switch", "2_hold") %}
          Hold Click 2
        {% elif is_state("sensor.kitchen_switch", "3_click_up") %}
          Quick Click 3
        {% elif is_state("sensor.kitchen_switch", "3_hold") %}
          Hold Click 3
        {% elif is_state("sensor.kitchen_switch", "4_hold") %}
          Hold Click 4
        {% else %}
          Off
        {% endif %}'
# Bedroom Hue Remote
    bedroom_switch_battery_level:
      friendly_name: 'Bedroom Remote Battery'
      value_template: '{{states.sensor.bedroom_switch.attributes.battery}}'
      unit_of_measurement: '%' 
    bedroom_remote:
      friendly_name: Hue Bedroom Remote
      value_template: '{% if is_state("sensor.bedroom_switch", "1_click_up") %} 
          Quick Click 1
        {% elif is_state("sensor.bedroom_switch", "1_hold") %}
          Hold Click 1
        {% elif is_state("sensor.bedroom_switch", "2_click_up") %}
          Quick Click 2
        {% elif is_state("sensor.bedroom_switch", "2_hold") %}
          Hold Click 2
        {% elif is_state("sensor.bedroom_switch", "3_click_up") %}
          Quick Click 3
        {% elif is_state("sensor.bedroom_switch", "3_hold") %}
          Hold Click 3
        {% elif is_state("sensor.bedroom_switch", "4_hold") %}
          Hold Click 4
        {% else %}
          Off
        {% endif %}'
# Office Hue Remote
    office_switch_battery_level:
      friendly_name: 'Office Remote Battery'
      value_template: '{{states.sensor.office_switch.attributes.battery}}'
      unit_of_measurement: '%'
    office_remote:
      friendly_name: Hue Office Remote
      value_template: '{% if is_state("sensor.office_switch", "1_click_up") %} 
          Quick Click 1
        {% elif is_state("sensor.office_switch", "1_hold") %}
          Hold Click 1
        {% elif is_state("sensor.office_switch", "2_click_up") %}
          Quick Click 2
        {% elif is_state("sensor.office_switch", "2_hold") %}
          Hold Click 2
        {% elif is_state("sensor.office_switch", "3_click_up") %}
          Quick Click 3
        {% elif is_state("sensor.office_switch", "3_hold") %}
          Hold Click 3
        {% elif is_state("sensor.office_switch", "4_hold") %}
          Hold Click 4
        {% else %}
          Off
        {% endif %}'