- platform: mqtt
  state_topic: 'home/downstairs/ac:37:43:78:3f:12'
  value_template: '{{ value_json.confidence }}'
  unit_of_measurement: '%'
  name: 'Toby Downstairs'

- platform: mqtt
  state_topic: 'home/upstairs/ac:37:43:78:3f:12'
  value_template: '{{ value_json.confidence }}'
  unit_of_measurement: '%'
  name: 'Toby Upstairs'

- platform: mqtt
  state_topic: 'home/downstairs/40:4e:36:51:87:41'
  value_template: '{{ value_json.confidence }}'
  unit_of_measurement: '%'
  name: 'Abi Downstairs'

- platform: mqtt
  state_topic: 'home/upstairs/40:4e:36:51:87:41'
  value_template: '{{ value_json.confidence }}'
  unit_of_measurement: '%'
  name: 'Abi Upstairs'

