# Camera Hangouts Bot Notifications
- alias: Motion Detected in back garden
  trigger:
    platform: state
    entity_id: binary_sensor.backyard_camera_back_garden_motion_detected
    to: 'detected'
  condition:
  - condition: state
    entity_id: device_tracker.google_pixel_abi
    state: 'away'
  - condition: state
    entity_id: device_tracker.google_pixel_xl_toby
    state: 'away'
  action:
    service: hangouts.send_message
    data_template:
      target: 
      - id: !secret notifier_noodlemctwoodle
      message: 
        - text: "There is motion in the back garden"

- alias: Motion Detected in front garden
  trigger:
    platform: state
    entity_id: binary_sensor.front_door_camera_motion_detected
    to: 'detected'
  condition:
  - condition: state
    entity_id: device_tracker.google_pixel_abi
    state: 'away'
  - condition: state
    entity_id: device_tracker.google_pixel_xl_toby
    state: 'away'
  action:
    service: hangouts.send_message
    data_template:
      target: 
      - id: !secret notifier_noodlemctwoodle
      message: 
        - text: "There is motion in the front garden"