# Google Hangouts Notifications
- alias: Heating on notification
  trigger:
    platform: state
    entity_id: sensor.living_room_thermostat_hvac_state
    to: heating
  action:
    service: hangouts.send_message
    data_template:
      target: 
      - id: !secret notifier_noodlemctwoodle
      message: 
        - text: "The heating is on"

- alias: Heating off notification
  trigger:
    platform: state
    entity_id: sensor.living_room_thermostat_hvac_state
    to: 'off'
  action:
    service: hangouts.send_message
    data_template:
      target: 
      - id: !secret notifier_noodlemctwoodle
      message: 
        - text: "The heating is off"
