# Google Home Notifications
- alias: Abi Is Home
  trigger:
    platform: state
    entity_id: sensor.abi_connected_ap
    from: Away
    to: Home
  action:
    service: tts.google_say
    entity_id: media_player.living_room_home
    data:
      message: 'Welcome Home'
